import { createAsyncThunk, createSlice } from '@reduxjs/toolkit';
import http from '../../api-client/http-client';

const initialState = {
  departments: [],
  status: 'idle',
};

// The function below is called a thunk and allows us to perform async logic. It
// can be dispatched like a regular action: `dispatch(incrementAsync(10))`. This
// will call the thunk with the `dispatch` function as the first argument. Async
// code can then be executed and other actions can be dispatched. Thunks are
// typically used to make async requests.
export const fetchDepartments = createAsyncThunk(
  'department/fetch',
  async () => {
    const response = await http.get(`departments`);
    // The value we return becomes the `fulfilled` action payload
    return response;
  }
);

export const deleteDepartment = createAsyncThunk(
  'department/delete',
  async (id) => {
    const response = await http.delete(`departments/${id}`);
    // The value we return becomes the `fulfilled` action payload
    if (response.result && !response.error)
      return { id }
  }
);

export const addDepartment = createAsyncThunk(
  'department/add',
  async (department) => {
    const response = await http.post(`departments`, department);
    // The value we return becomes the `fulfilled` action payload
    return response;
  }
);

export const updateDepartment = createAsyncThunk(
  'department/update',
  async (toUpdate) => {
    const response = await http.patch(`departments/${toUpdate.id}`, toUpdate);
    // The value we return becomes the `fulfilled` action payload
    return response;
  }
);

export const departmentSlice = createSlice({
  name: 'department',
  initialState,
  // The `reducers` field lets us define reducers and generate associated actions
  reducers: {
  },
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: (builder) => {
    builder
      .addCase(fetchDepartments.pending, (state) => {
        state.status = 'loading';
      })
      .addCase(fetchDepartments.fulfilled, (state, action) => {
        state.status = 'idle';
        state.departments = action.payload;
      })
      .addCase(deleteDepartment.pending, (state) => {
        state.status = 'loading';
      })
      .addCase(deleteDepartment.fulfilled, (state, action) => {
        state.status = 'idle';
        if (action.payload?.id) {
          const toDelete = action.payload;
          const index = state.departments.findIndex(dep => dep.id === toDelete.id);

          // Redux Toolkit allows us to write "mutating" logic in reducers. It
          // doesn't actually mutate the state because it uses the Immer library,
          // which detects changes to a "draft state" and produces a brand new
          // immutable state based off those changes
          state.departments.splice(index, 1);
        }
      })
      .addCase(addDepartment.pending, (state) => {
        state.status = 'loading';
      })
      .addCase(addDepartment.fulfilled, (state, action) => {
        state.status = 'idle';
        state.departments.push(action.payload)
      })
      .addCase(updateDepartment.pending, (state) => {
        state.status = 'loading';
      })
      .addCase(updateDepartment.fulfilled, (state, action) => {
        state.status = 'idle';
        state.departments = state.departments.map(dep => {
          if (action.payload.id === dep.id) {
            return { ...dep, ...action.payload }
          }
          return dep
        })
      })
  },
});


// The function below is called a selector and allows us to select a value from
// the state. Selectors can also be defined inline where they're used instead of
// in the slice file. For example: `useSelector((state: RootState) => state.counter.value)`
export const selectDepartments = (state) => state.department.departments;

export default departmentSlice.reducer;