version: '3.4'

services:
  api:
    image: store-api
    build:
      context: ./
      dockerfile: ./api/Dockerfile
    container_name: api_container
    hostname: apihost
    environment:
      NODE_ENV: production
    expose:
      - 3333
    ports:
      - 3333:3333
    networks:
      - store_default
  front:
    image: react
    build:
      context: ./
      dockerfile: ./store/Dockerfile
    container_name: front_container
    hostname: fronthost
    expose:
      - 4200
    ports:
      - 4200:4200
    networks:
      - store_default

networks:
  store_default:
    external: true
